### ISSUE TITLE
支持哪些ES版本呀？

### ISSUE THREAD

**Issue by aqlu** [farmerx/ElasticHD#1]
下载https://github.com/farmerx/ElasticHD/releases/download/1.0/elasticHD_darwin_amd64.zip，测试ES 1.5.2、5.1.2都显示未连接。
![image](https://user-images.githubusercontent.com/5010463/26916268-3a9852a8-4c5c-11e7-9614-8c7450a52b24.png)

**Comment by farmerx** [comment]
1.7到5.0 都是支持的啊

**Comment by farmerx** [comment]
![wx20170608-154005](https://user-images.githubusercontent.com/24504247/26917413-ca77a2d0-4c60-11e7-81e3-01924fb34431.png)
我本地的测试过2.0以上版本，你看一下这个是5.2的

**Comment by aqlu** [comment]
你尝试连接非本机的ES的呢？我下载ElasticHD 1.0 elasticHD_darwin_amd64.zip包，连接5.1.2版本的ES，点击“Connect”后，集群健康状态显示未连接，其它数据也未获取到。

![image](https://user-images.githubusercontent.com/5010463/26917556-4d8806d8-4c61-11e7-90ac-bade4fe1ea42.png)

**Comment by farmerx** [comment]
我尝试链接过非本地的es , 你浏览器能直接访问172.19.55.56吗？ 或者我们发邮件，我看一下实际的情况

**Comment by farmerx** [comment]
Hi！ 我正在下载5.1.2的elasticsearch ，
我想询问一下，你的浏览器能直接访问172.19.65.66：9200这个es吗？如果有数据的话，截图回复我一下

**Comment by aqlu** [comment]
可以的访问的哦。我邮箱：angus.aqlu@gmail.com

`
{
    "name": "lin-65-66.localdomain",
    "cluster_name": "qmkf_elasticsearch",
    "cluster_uuid": "hpRvFGk0QNOYAPlmqzgn9w",
    "version": {
        "number": "5.1.1",
        "build_hash": "5395e21",
        "build_date": "2016-12-06T12:36:15.409Z",
        "build_snapshot": false,
        "lucene_version": "6.3.0"
    },
    "tagline": "You Know, for Search"
}
`

**Comment by aqlu** [comment]
找到原因了，是我环境变量里面设置了`http_proxy`，应该是你用的某个http库读取了这个变量。

**Comment by farmerx** [comment]
那我问题关闭了啊

**Comment by aqlu** [comment]
好的 🙂
