### ISSUE TITLE
错误的json请求也有返回值

### ISSUE THREAD

**Issue by wclssdn** [farmerx/ElasticHD#11]
随便填写一个错误的json，发起请求，有正常的返回值。
错误的json如：`{"query":{"match2_all":{}}}`
返回值同`{"query":{"match_all":{}}}`一致。

期望能原样返回es给出的错误，如：`{"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [match2_all]","line":4,"col":23}],"type":"parsing_exception","reason":"no [query] registered for [match2_all]","line":4,"col":23},"status":400}`

**Comment by farmerx** [comment]
hi！ 你选择post 查询方式， get f方式默认不带textarea 里面的搜索语句的

**Comment by wclssdn** [comment]
get不带怎么search呢？search请求就是get的。并且要带body的。。。因为查询就是很复杂的~

**Comment by farmerx** [comment]
目前 http请求get是不带body体的

**Comment by wclssdn** [comment]
跟ES的逻辑不一致了~ Kibana是支持的~

**Comment by farmerx** [comment]
那下个版本我修改一下。这个版本先选择post 方式查询吧， 我是保持了和head 插件一致。 欢迎补充提出问题。。。。共同改进
