### ISSUE TITLE
为什么dashboard页面很多信息都取不到？

### ISSUE THREAD

**Issue by hexian55** [farmerx/ElasticHD#16]
hi

![image](https://user-images.githubusercontent.com/16074700/27760770-daf8a4dc-5e81-11e7-8af4-3e59c724f028.png)
我在dashboard页面发现很多指标都是0和未知    
比如jvm   mem    es version也是未知

我es的版本是5.2.1

上面是我的截图

**Comment by hexian55** [comment]
另外提一个小建议，能不能支持多集群展示，同时配置多个集群，自由切换集群看每个集群分别的状态，以及有一个集群列表页

**Comment by farmerx** [comment]
这是被修改过的es吧？这个多节点正在做

**Comment by hexian55** [comment]
没有没有，这个es我用的是官方的    没有改动过

**Comment by hexian55** [comment]
抱歉  我下错版本了

**Comment by farmerx** [comment]
好吧。。。。
