### ISSUE TITLE
centos 怎么安装呢 

### ISSUE THREAD

**Issue by kiwimg** [farmerx/ElasticHD#19]
centos下 怎么安装呢 我安装失败

提示缺少 htmlView command not find

**Comment by farmerx** [comment]
你是下载的安装包吗？ 如果是安装包的话，是因为你没有桌面浏览器的原因，请忽略，外部访问你浏览器的ip+port 就好了

**Comment by farmerx** [comment]
close

**Comment by Luolired** [comment]
elastichd 可指定ip端口运行elastichd ./ElasticHD -p 127.0.0.1:9800 默认 ip和端口也是这个 
这一步怎么装的？ 都没有elastichd呀，只有main.c
