### ISSUE TITLE
怎么运行啊

### ISSUE THREAD

**Issue by robinWeng0315** [farmerx/ElasticHD#2]
下载了elasticHD_linux_amd64.zip 这个包，但是不知道怎么运行

**Comment by farmerx** [comment]
unzip elasticHD_linux_amd64.zip
chmod 0777 elasticHD
./elasticHD   

默认可以访问你linux 的ip+9800 端口 当然也是可以指定端口的

**Comment by robinWeng0315** [comment]
可以运行了，谢谢

**Comment by farmerx** [comment]
这是我的疏忽，确实没有运行方法。一会补充上，非常感谢。好评的话给个星星。

**Comment by farmerx** [comment]
已解决

**Comment by yangzhiw** [comment]
zsh: exec format error:  es/ElasticHD

**Comment by lizhenjuan** [comment]
我也报错 ：zsh: exec format error: ./ElasticHD
