### ISSUE TITLE
 { "error": "syntax error at position 104" } sql转换出错，功能还不够强大。

### ISSUE THREAD

**Issue by laoyang360** [farmerx/ElasticHD#21]
select * from kwindex where user_name.keyword like  '%sangfor123443%' or  tags.keyword like '%大hao%';
这种sql转换提示错误"  { "error": "syntax error at position 104" }

**Comment by farmerx** [comment]
你把分号去掉就好了

**Comment by farmerx** [comment]
![wx20170811-171806](https://user-images.githubusercontent.com/24504247/29207510-fe78162a-7eb8-11e7-97cc-bd20916b9aa1.png)
