### ISSUE TITLE
项目不再更新了吗？

### ISSUE THREAD

**Issue by chenyg0911** [farmerx/ElasticHD#23]
挺酷的。不更新就可惜了。

**Comment by farmerx** [comment]
更新的。。。。不过有一段时间没做了。工作有点忙

**Comment by chenyg0911** [comment]
好消息！希望有空继续完善。现在free的好的监控少，希望能加强这一块。至于SQL，另外一个不错的项目elasticsearh-sql在做，据说官方后续可能也会提供，可以暂时放一放。

2017-11-02 10:14 GMT+08:00 Farmerx <notifications@github.com>:
