### ISSUE TITLE
exec: "xdg-open": executable file not found in $PATH

### ISSUE THREAD

**Issue by laoyang360** [farmerx/ElasticHD#3]
^C[root@6c5ea0]# ./ElasticHD  -p 100.0.111.136:9800
To view elasticHD console open http://100.0.111.136:9800 in browser
exec: "xdg-open": executable file not found in $PATH

centos64 安装了elasticHD_linux_amd64.zip，效果还不错。就是会有上面的错误。（倒是没有影响）。

**Comment by farmerx** [comment]
这个问题是的Linux没有brower 造成的，程序启动的时候会默认打开浏览器，如果没有的话，会抛出这个错误
