### ISSUE TITLE
windows版本，界面不显示

### ISSUE THREAD

**Issue by tony43400141** [farmerx/ElasticHD#4]
应用： window ElasticHd  1.2 amd64 版本  打开界面样式不显示 ，白屏

![image 4](https://user-images.githubusercontent.com/11306626/27318919-594f8590-55c1-11e7-8968-3410e86ec8bf.png)
![image 5](https://user-images.githubusercontent.com/11306626/27318933-6e8c9fc4-55c1-11e7-8650-7be1589d674e.png)

**Comment by farmerx** [comment]
稍等我找个64 Windows在测试一下

**Comment by farmerx** [comment]
hi! 能说一下你是怎么个环境吗，什么浏览器？ 是不是禁止加载css 样式表，或者您用的是ie9一下的版本

![image](https://user-images.githubusercontent.com/24504247/27322207-c89a90f8-55cf-11e7-8b06-7a438179862b.png)

**Comment by farmerx** [comment]
我刚下载的，本地windows10个windows7 没有发现一场，浏览器chrome,

**Comment by farmerx** [comment]
还有问题的话，你在打开issue, 我先关掉了。
