### ISSUE TITLE
Docker Quick Start

### ISSUE THREAD

**Issue by llitfkitfk** [farmerx/ElasticHD#6]
Quick Start:
```
docker run -p 9200:9200 -d --name elasticsearch elasticsearch
docker run -p 9800:9800 -d --link elasticsearch:demo containerize/elastichd
```

Open http://localhost:9800 in Browser
Connect with http://demo:9200

---

Image link: https://hub.docker.com/r/containerize/elastichd/

---

Screen Shot:
![image](https://user-images.githubusercontent.com/2404785/27365726-2dcda1b4-5674-11e7-948c-f0d3da6418c3.png)

**Comment by farmerx** [comment]
赞一个👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by llitfkitfk** [comment]
pr: #8

**Comment by farmerx** [comment]
已经接受
