### ISSUE TITLE
若干建议

### ISSUE THREAD

**Issue by hktalent** [farmerx/ElasticHD#84]
- 状态为yellow，建议提供在线修复方案，
- 如何快速引导完成复杂的查询（例子）
  * 多条件查询
  * 数字类型的大于 and 等于，范围查询
  * 多字段组合查询
  * 复杂结构的模糊查询

**Comment by hktalent** [comment]
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/18223385/143733807-c2d1e732-eda6-42f6-8fce-4e50ab192132.png">
再建议：支持点击进入

<img width="441" alt="image" src="https://user-images.githubusercontent.com/18223385/143733846-a44e8f83-3c1a-4b9f-a8b1-f9197733b7f3.png">

支持下拉选择

**Comment by 1340691923** [comment]
请使用我的开源项目 https://github.com/1340691923/ElasticView
